name: Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  docker-compose-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Start Docker Compose
      run: |
        docker compose -f pwd.yml up -d

    - name: Verify Docker Containers
      run: |
        docker ps

    - name: Clean up
      run: |
        docker-compose down
