version: '3'
services:
  frappe:
    build: .
    ports:
      - "8000:8000"
    environment:
      MYSQL_ROOT_PASSWORD: root
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data:
